networks:
  leluchat:
    name: leluchat
    external: true
services:
  arsenal:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    container_name: leluchat_arsenal
    environment:
      - DJANGO_CONSUME_MESSAGES=True
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    networks:
      - leluchat
