networks:
  auth:
    name: auth
    external: true
services:
  arsenal:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    container_name: leluchat_arsenal
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    networks:
      - auth
