# pylint: skip-file
# Generated by Django 4.2.6 on 2023-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsenal', '0004_sender_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='Sender',
        ),
    ]
